GET http://localhost:3001/

###
GET http://localhost:3001/api/notes

###
POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content": "Esta es la segunda prueba que estamos haciendo",
    "important": true,
    "userId": "6a2742eba9fdf3c240466917"
}

###
POST http://localhost:3001/api/users
Content-Type: application/json

{
  "username": "O1311",
  "name": "Oswaldo Rodríguez",
  "password": "oswaldo"
}

###
GET http://localhost:3001/api/users

###
POST http://localhost:3001/api/login
Content-Type: application/json

{
  "username": "O1311",
  "password": "oswaldo"
}

###
POST http://localhost:3001/api/notes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik8xMzExIiwiaWQiOiI2YTI3NDJlYmE5ZmRmM2MyNDA0NjY5MTciLCJpYXQiOjE3ODEwMjAzMzV9.TeyVhNDb6oo8SBAHch9b4EsckBWHAWCSwxkyk7ybfgk

{
  "content": "Single page apps use token based auth",
  "important": false
}
